---
title: "Model, View, Controller"
type: "article"
description: "How can Objects, Databases, and Software come together to help us create Web Apps?"
tags: "mvc, objects, databases, sql, rails, activerecord, js"
