source 'https://rubygems.org'

gem 'activerecord', '~> 4.2'
gem 'pg'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'faker'

group :test, :development do
  gem 'capybara'
  gem 'pry'
  gem 'rspec'
end
