---
title: "Factory Girl Associations"
type: "article"
description: "Build multiple records in a single call to simplify test setup using Factory Girl associations."
tags: "testing, factory_girl, tdd"
