development:
  adapter: postgresql
  encoding: unicode
  database: breakfast-cereal-battle_development
  pool: 5
  username:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: breakfast-cereal-battle_test
  pool: 5
  username:
  password:
