import React from 'react';

const Article = () => {
  return (
    <article>
      <h2>Lorem Ipsum</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac volutpat orci, eu ornare metus. Aliquam tristique, risus at tincidunt ornare, nibh risus faucibus augue, non varius erat dui at tortor. Nulla facilisi. Donec efficitur est est, et sagittis odio iaculis id. Proin vitae felis vulputate, laoreet nisl id, aliquet dolor. Phasellus condimentum vel lacus sed condimentum. Proin accumsan libero eget ullamcorper ornare. Proin vulputate tortor vitae dictum mollis. Sed vitae molestie tellus. Nunc quis porttitor ex, in pellentesque erat. Aliquam feugiat, sapien quis sodales ultrices, nisi elit efficitur risus, vel ornare neque leo in erat. Donec non purus sit amet eros interdum pharetra.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac volutpat orci, eu ornare metus. Aliquam tristique, risus at tincidunt ornare, nibh risus faucibus augue, non varius erat dui at tortor. Nulla facilisi. Donec efficitur est est, et sagittis odio iaculis id. Proin vitae felis vulputate, laoreet nisl id, aliquet dolor. Phasellus condimentum vel lacus sed condimentum. Proin accumsan libero eget ullamcorper ornare. Proin vulputate tortor vitae dictum mollis. Sed vitae molestie tellus. Nunc quis porttitor ex, in pellentesque erat. Aliquam feugiat, sapien quis sodales ultrices, nisi elit efficitur risus, vel ornare neque leo in erat. Donec non purus sit amet eros interdum pharetra.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac volutpat orci, eu ornare metus. Aliquam tristique, risus at tincidunt ornare, nibh risus faucibus augue, non varius erat dui at tortor. Nulla facilisi. Donec efficitur est est, et sagittis odio iaculis id. Proin vitae felis vulputate, laoreet nisl id, aliquet dolor. Phasellus condimentum vel lacus sed condimentum. Proin accumsan libero eget ullamcorper ornare. Proin vulputate tortor vitae dictum mollis. Sed vitae molestie tellus. Nunc quis porttitor ex, in pellentesque erat. Aliquam feugiat, sapien quis sodales ultrices, nisi elit efficitur risus, vel ornare neque leo in erat. Donec non purus sit amet eros interdum pharetra.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac volutpat orci, eu ornare metus. Aliquam tristique, risus at tincidunt ornare, nibh risus faucibus augue, non varius erat dui at tortor. Nulla facilisi. Donec efficitur est est, et sagittis odio iaculis id. Proin vitae felis vulputate, laoreet nisl id, aliquet dolor. Phasellus condimentum vel lacus sed condimentum. Proin accumsan libero eget ullamcorper ornare. Proin vulputate tortor vitae dictum mollis. Sed vitae molestie tellus. Nunc quis porttitor ex, in pellentesque erat. Aliquam feugiat, sapien quis sodales ultrices, nisi elit efficitur risus, vel ornare neque leo in erat. Donec non purus sit amet eros interdum pharetra.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac volutpat orci, eu ornare metus. Aliquam tristique, risus at tincidunt ornare, nibh risus faucibus augue, non varius erat dui at tortor. Nulla facilisi. Donec efficitur est est, et sagittis odio iaculis id. Proin vitae felis vulputate, laoreet nisl id, aliquet dolor. Phasellus condimentum vel lacus sed condimentum. Proin accumsan libero eget ullamcorper ornare. Proin vulputate tortor vitae dictum mollis. Sed vitae molestie tellus. Nunc quis porttitor ex, in pellentesque erat. Aliquam feugiat, sapien quis sodales ultrices, nisi elit efficitur risus, vel ornare neque leo in erat. Donec non purus sit amet eros interdum pharetra.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac volutpat orci, eu ornare metus. Aliquam tristique, risus at tincidunt ornare, nibh risus faucibus augue, non varius erat dui at tortor. Nulla facilisi. Donec efficitur est est, et sagittis odio iaculis id. Proin vitae felis vulputate, laoreet nisl id, aliquet dolor. Phasellus condimentum vel lacus sed condimentum. Proin accumsan libero eget ullamcorper ornare. Proin vulputate tortor vitae dictum mollis. Sed vitae molestie tellus. Nunc quis porttitor ex, in pellentesque erat. Aliquam feugiat, sapien quis sodales ultrices, nisi elit efficitur risus, vel ornare neque leo in erat. Donec non purus sit amet eros interdum pharetra.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac volutpat orci, eu ornare metus. Aliquam tristique, risus at tincidunt ornare, nibh risus faucibus augue, non varius erat dui at tortor. Nulla facilisi. Donec efficitur est est, et sagittis odio iaculis id. Proin vitae felis vulputate, laoreet nisl id, aliquet dolor. Phasellus condimentum vel lacus sed condimentum. Proin accumsan libero eget ullamcorper ornare. Proin vulputate tortor vitae dictum mollis. Sed vitae molestie tellus. Nunc quis porttitor ex, in pellentesque erat. Aliquam feugiat, sapien quis sodales ultrices, nisi elit efficitur risus, vel ornare neque leo in erat. Donec non purus sit amet eros interdum pharetra.</p>
  </article>
  );
};

export default Article;
