# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: team_dunks_starbucks_for_clinic_development
  pool: 5
  username:
  password:

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: team_dunks_starbucks_for_clinic_test
  pool: 5
  username:
  password:

# Configure the database used when in the production environment
production:
  adapter: postgresql
  encoding: unicode
  database: team_dunks_starbucks_for_clinic_production
  pool: 5
  username:
  password:
