# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a3c0010c4710227aacfc56399de15796795c627e4a2eef5b3019412066ce964e4939dc6bdca5c83fc73e9110baabbfbd2e53ae94c7bca6f5a5759438957b2bc

test:
  secret_key_base: d30672e334267d3a74ed54c371fcec88245fd926a9d500f199bc864b6dc9a5e3445c8b363651affeefefaf04f3d4e725ea103a80e78da4ccce532491c8cb7e89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
